openapi: 3.0.1
info:
  title: My API
  version: 1.0.0
servers:
- url: /
paths:
  /example:
    get:
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Example endpoint
      x-accepts: application/json
components:
  schemas: {}
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http

