openapi: 3.0.1
info:
  title: My API
  version: 1.0.0
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /example:
    get:
      summary: Example endpoint
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK
